<template>
  <div class="container">
    <span class="body-2 ml-5 mb-0">나의 랭킹 ⭐️</span>
    <v-row no-gutters justify="center">
      <v-avatar class="mr-2 ml-2" size="80" color="white">
        <img :src="character[user.characterId - 1][2]" alt="John" />
      </v-avatar>
    </v-row>
    <v-row justify="center" class="caption font-weight-black">
      <span class="tracking-in-expand-fwd">{{ me.username }} 님은 현재 {{ me.rank }} 등 🔥</span>
    </v-row>
    <!-- <v-card hover elevation="5" class="pl-3 ml-5 mr-5 mt-2" color="#6782D4" dark>
        <v-card-title class="body-1"> {{ me.rank }}등 {{ me.username }} </v-card-title>
        <v-card-subtitle class="body-2 pb-2">
        {{ me.exer }}
        </v-card-subtitle>
    </v-card> -->
  </div>
</template>

<script>
import { mapGetters } from "vuex";

export default {
  computed: {
    ...mapGetters("rank", ["GE_ME"]),
    ...mapGetters(["user", "character"]),
    me() {
      return this.GE_ME;
    },
  },
};
</script>

<style scoped>
.tracking-in-expand-fwd {
  -webkit-animation: tracking-in-expand-fwd 3s
    cubic-bezier(0.215, 0.61, 0.355, 1) both;
  animation: tracking-in-expand-fwd 3s cubic-bezier(0.215, 0.61, 0.355, 1) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-10-28 8:47:57
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tracking-in-expand-fwd
 * ----------------------------------------
 */
@-webkit-keyframes tracking-in-expand-fwd {
  0% {
    letter-spacing: -0.5em;
    -webkit-transform: translateZ(-700px);
    transform: translateZ(-700px);
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
    opacity: 1;
  }
}
@keyframes tracking-in-expand-fwd {
  0% {
    letter-spacing: -0.5em;
    -webkit-transform: translateZ(-700px);
    transform: translateZ(-700px);
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
    opacity: 1;
  }
}
</style>
