<template>
  <div class="mt-2">
    <span class="body-2 ml-5 mb-0">나의 캐릭터 🤝</span>
    <v-row no-gutters justify="center" align="center">
      <v-avatar class="mr-2 ml-2">
        <img src="../../assets/따봉아거.png" alt="John" />
      </v-avatar>
      <v-avatar class="mr-3">
        <img src="../../assets/곰1.png" alt="John" />
      </v-avatar>
      <v-avatar class="mr-3">
        <img src="../../assets/악어1.png" alt="John" />
      </v-avatar>

      <v-avatar class="mr-3">
        <img src="../../assets/작은하트라무.png" alt="John" />
      </v-avatar>

      <v-avatar class="mr-3">
        <img src="../../assets/토끼1.png" alt="John" />
      </v-avatar>
    </v-row>
    <v-row no-gutters justify="center" align="center">
      <v-chip-group
        v-model="selection"
        active-class="orange--text text--darken-4"
        class="font-weight-black"
        mandatory
      >
        <v-chip class="jello-vertical">콜리</v-chip>
        <v-chip class="jello-vertical">비비</v-chip>
        <v-chip class="jello-vertical">아거</v-chip>
        <v-chip class="jello-vertical">라무</v-chip>
        <v-chip class="jello-vertical">토끼</v-chip>
      </v-chip-group>
    </v-row>
  </div>
</template>

<script>
export default {
  data() {
    return {
      selection: 0,
    };
  },
};
</script>

<style scoped>
.v-chip:focus.jello-vertical {
  -webkit-animation: jello-vertical 0.9s both;
  animation: jello-vertical 0.9s both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-10-21 15:0:19
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation jello-vertical
 * ----------------------------------------
 */
@-webkit-keyframes jello-vertical {
  0% {
    -webkit-transform: scale3d(1, 1, 1);
    transform: scale3d(1, 1, 1);
  }
  30% {
    -webkit-transform: scale3d(0.75, 1.25, 1);
    transform: scale3d(0.75, 1.25, 1);
  }
  40% {
    -webkit-transform: scale3d(1.25, 0.75, 1);
    transform: scale3d(1.25, 0.75, 1);
  }
  50% {
    -webkit-transform: scale3d(0.85, 1.15, 1);
    transform: scale3d(0.85, 1.15, 1);
  }
  65% {
    -webkit-transform: scale3d(1.05, 0.95, 1);
    transform: scale3d(1.05, 0.95, 1);
  }
  75% {
    -webkit-transform: scale3d(0.95, 1.05, 1);
    transform: scale3d(0.95, 1.05, 1);
  }
  100% {
    -webkit-transform: scale3d(1, 1, 1);
    transform: scale3d(1, 1, 1);
  }
}
@keyframes jello-vertical {
  0% {
    -webkit-transform: scale3d(1, 1, 1);
    transform: scale3d(1, 1, 1);
  }
  30% {
    -webkit-transform: scale3d(0.75, 1.25, 1);
    transform: scale3d(0.75, 1.25, 1);
  }
  40% {
    -webkit-transform: scale3d(1.25, 0.75, 1);
    transform: scale3d(1.25, 0.75, 1);
  }
  50% {
    -webkit-transform: scale3d(0.85, 1.15, 1);
    transform: scale3d(0.85, 1.15, 1);
  }
  65% {
    -webkit-transform: scale3d(1.05, 0.95, 1);
    transform: scale3d(1.05, 0.95, 1);
  }
  75% {
    -webkit-transform: scale3d(0.95, 1.05, 1);
    transform: scale3d(0.95, 1.05, 1);
  }
  100% {
    -webkit-transform: scale3d(1, 1, 1);
    transform: scale3d(1, 1, 1);
  }
}
</style>
